/* Generated By:JavaCC: Do not edit this line. PCCConstants.java */
package javacc;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface PCCConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int QUOTEMARK = 1;
  /** RegularExpression Id. */
  int ENDQUOTE = 2;
  /** RegularExpression Id. */
  int STRING_CHAR = 3;
  /** RegularExpression Id. */
  int OPEN_SQUARE = 4;
  /** RegularExpression Id. */
  int CLOSE_SQUARE = 5;
  /** RegularExpression Id. */
  int COMMA = 6;
  /** RegularExpression Id. */
  int INCREMENT = 7;
  /** RegularExpression Id. */
  int DECREMENT = 8;
  /** RegularExpression Id. */
  int EQUALS = 9;
  /** RegularExpression Id. */
  int OPERATOR = 10;
  /** RegularExpression Id. */
  int PRINT = 11;
  /** RegularExpression Id. */
  int ADD = 12;
  /** RegularExpression Id. */
  int TO = 13;
  /** RegularExpression Id. */
  int SET = 14;
  /** RegularExpression Id. */
  int LET = 15;
  /** RegularExpression Id. */
  int BE = 16;
  /** RegularExpression Id. */
  int IS = 17;
  /** RegularExpression Id. */
  int AND = 18;
  /** RegularExpression Id. */
  int NOT = 19;
  /** RegularExpression Id. */
  int IF = 20;
  /** RegularExpression Id. */
  int ENDIF = 21;
  /** RegularExpression Id. */
  int COMMENT_STARTER = 22;
  /** RegularExpression Id. */
  int END_COMMENT = 23;
  /** RegularExpression Id. */
  int COMMENT_STRING = 24;
  /** RegularExpression Id. */
  int VAR_NAME = 25;
  /** RegularExpression Id. */
  int NUMBER = 26;
  /** RegularExpression Id. */
  int NEWLINE = 27;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int STRING_STATE = 1;
  /** Lexical state. */
  int COMMENT_MODE = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\\"\"",
    "<ENDQUOTE>",
    "<STRING_CHAR>",
    "\"[\"",
    "\"]\"",
    "\",\"",
    "\"+\"",
    "\"-\"",
    "<EQUALS>",
    "<OPERATOR>",
    "<PRINT>",
    "<ADD>",
    "<TO>",
    "<SET>",
    "<LET>",
    "<BE>",
    "<IS>",
    "<AND>",
    "<NOT>",
    "<IF>",
    "<ENDIF>",
    "<COMMENT_STARTER>",
    "<END_COMMENT>",
    "<COMMENT_STRING>",
    "<VAR_NAME>",
    "<NUMBER>",
    "\"\\n\"",
    "\"\\r\"",
    "\" \"",
    "\"\\t\"",
  };

}
