/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test;

public class PCC_Tests {
//    
//    @Test 
//    public void run() throws IOException {
//    	String ourCode = Files.readAllLines(new File("prog.pcc").toPath()).stream().collect(Collectors.joining("\n"));
//    	PCC.parse(ourCode);
//    }
}
